import "./globals.css";
import { Rubik } from "next/font/google";

//components
import Navbar from "./components/Navbar";
import { Suspense } from "react";
import Loading from "./loading";
import { AuthProvider } from "./Providers";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Help-Desk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
